sudo: required

services:
  - docker

language: go

go:
- 1.8.3

deploy:
  provider: script
  script:
    - make
    - make docker
    - make push
  on:
    tags: true
    all_branches: true

deploy:
  provider: script
  script:
    - make crossbuild
    - make release
  on:
    tags: true