sudo: required

services:
  - docker

language: go

go:
- 1.8.3

after_success:
  - make
  - make docker
  - make push

deploy:
  provider: script
  script:
    - make crossbuild
    - make release
  on:
    tags: true